name: Developer_Branch_CI

on: [workflow_call]
jobs:
  CI-Steps:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Unit Tests
        run: echo unit tests

      - name: Integration Tests
        run: echo Integration Tests

      - name: code quality
        run: sonar-scanner -Dsonar.host.url=http://sonarqube-internal.madhanmohanreddy.tech:9000 -Dsonar.login=${SONAR_USER} -Dsonar.password=${SONAR_PASS} -Dsonar.projectKey=expense-backend
        env:
          SONAR_USER: ${{ secrets.SONAR_USER }}
          SONAR_PASS: ${{ secrets.SONAR_PASS }}
