name: Release_Tags.yml

on:
  workflow_call:
    inputs:
      service_name:
        type: string
        required: true


jobs:
  CI_Steps:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: SAST scans
        run: echo SAST scans

      - name: SCA scans
        run: echo SCA scans

      - name: secret detection in source code
        run: echo secret detection in source code

      - name: download dependencies
        if: inputs.service_name == 'expense-backend'
        run: install  npm

      - name: artifact produce
        env:
          service_name: ${{ inputs.service_name }}
          ARTIFACTORY_CREDENTIALS: ${{ secrets.ARTIFACTORY_CREDENTIALS }}
        run:  |
          zip -r ${GITHUB_REF_NAME}.zip * -x .github
          curl -v -X PUT -u ${ARTIFACTORY_CREDENTIALS} -T ${GITHUB_REF_NAME}.zip http://artifactory-internal.madhanmohanreddy.tech:8081/artifactory/${service_name}/${GITHUB_REF_NAME}.zip 
